import assert from 'node:assert/strict';
import { openDatabase } from './db.js';
import { EventLog } from './events.js';
import { SessionStore } from './sessions.js';
import { BadgerWorkflow } from './state-machine.js';

const db=openDatabase(':memory:'), store=new SessionStore(db), events=new EventLog(db), workflow=new BadgerWorkflow(store,events);
const created=store.create({hostName:'Host',goal:'Demo'});
store.addParticipant(created,{name:'Alex',phone:'+15550000001'});
store.addParticipant(created,{name:'Priya',phone:'+15550000002'});
const session=store.get(created.id)!;
workflow.start(session);
for(const p of session.participants) workflow.recordPreferences(session,p,{availability:['friday_after_8','saturday_afternoon'],hardVetoes:[],preferences:['imax'],flexibility:.7,summary:'Friday or Saturday works'});
assert.equal(session.status,'PROPOSING');
assert.ok(session.selectedCandidateId);
assert.equal(events.list(session.id).at(-1)?.type,'plan.proposed');
const rejectedCandidateId=session.selectedCandidateId;
workflow.rejectCandidate(session,session.participants[0]!);
assert.equal(session.status,'PROPOSING');
assert.notEqual(session.selectedCandidateId,rejectedCandidateId);
assert.equal(session.candidates.find((candidate)=>candidate.id===session.selectedCandidateId)?.slot,'saturday_afternoon');
assert.equal(events.list(session.id).some((event)=>event.type==='session.cancelled'),false);
assert.equal(events.list(session.id).some((event)=>event.type==='proposal.rejected'),true);

const conflicted=store.create({hostName:'Host',goal:'Conflict demo'});
store.addParticipant(conflicted,{name:'Flexible',phone:'+15550000003'});
store.addParticipant(conflicted,{name:'Available',phone:'+15550000004'});
const conflictSession=store.get(conflicted.id)!;
workflow.start(conflictSession);
workflow.recordPreferences(conflictSession,conflictSession.participants[0]!,{availability:['saturday_afternoon'],hardVetoes:[],preferences:['imax'],flexibility:.9,summary:'Could flex'});
workflow.recordPreferences(conflictSession,conflictSession.participants[1]!,{availability:['friday_after_8'],hardVetoes:[],preferences:['imax'],flexibility:.1,summary:'Friday only'});
assert.equal(conflictSession.status,'RESOLVING');
const target=conflictSession.participants.find((participant)=>participant.status==='NEEDS_FOLLOWUP');
assert.equal(target?.name,'Flexible');
workflow.acceptFlexibility(conflictSession,target!);
assert.equal(conflictSession.status,'PROPOSING');
console.info('workflow test passed');
